// <auto-generated />
using System;
using GestaoProdutos.Infra.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GestaoProdutos.Infra.Migrations
{
    [DbContext(typeof(ContextoBD))]
    [Migration("20240117200045_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("GestaoProdutos.Dominio.Modelos.Entidades.Fornecedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CNPJ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Fornecedores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CNPJ = "55.758.816/0001-70",
                            Descricao = "Bosch"
                        },
                        new
                        {
                            Id = 2,
                            CNPJ = "78.738.236/0001-17",
                            Descricao = "Moura"
                        },
                        new
                        {
                            Id = 3,
                            CNPJ = "89.752.353/0001-51",
                            Descricao = "Sachs"
                        },
                        new
                        {
                            Id = 4,
                            CNPJ = "98.821.249/0001-62",
                            Descricao = "Osram"
                        },
                        new
                        {
                            Id = 5,
                            CNPJ = "80.905.484/0001-57",
                            Descricao = "Goodyear"
                        },
                        new
                        {
                            Id = 6,
                            CNPJ = "40.232.831/0001-03",
                            Descricao = "Dunlop"
                        },
                        new
                        {
                            Id = 7,
                            CNPJ = "55.784.902/0001-58",
                            Descricao = "Valeo"
                        });
                });

            modelBuilder.Entity("GestaoProdutos.Dominio.Modelos.Entidades.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DataFabricacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataValidade")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FornecedorId")
                        .HasColumnType("int");

                    b.Property<int>("Situacao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FornecedorId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("GestaoProdutos.Dominio.Modelos.Entidades.Produto", b =>
                {
                    b.HasOne("GestaoProdutos.Dominio.Modelos.Entidades.Fornecedor", "Fornecedor")
                        .WithMany("Produtos")
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("GestaoProdutos.Dominio.Modelos.Entidades.Fornecedor", b =>
                {
                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
